apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobland-legacy-php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      restartPolicy: Always

      initContainers:
      - name: gobland-legacy-php-init
        image: busybox
        volumeMounts:
        - name: code
          mountPath: /code
        command: ["/bin/sh"]
        args: [
         "-c",
         "(
              wget   https://github.com/lordslair/foobar/archive/master.zip -O /tmp/foobar.zip &&
              unzip  /tmp/foobar.zip -d tmp &&
              cp -a  /tmp/foobar-master/k8s/gl-legacy/php/entrypoint.sh /code/entrypoint.sh &&
              rm -rf /tmp/foobar-master /tmp/foobar.zip
          ) || echo 1"
        ]

      containers:
      - name: gobland-legacy-php
        image: php:5.5.35-fpm-alpine
        command: ["/code/entrypoint.sh"]
        volumeMounts:
        - mountPath: /code
          name: code

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: gobland-legacy-code-php
