apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gobland-legacy-code-php
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
