apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gobland-legacy-mysql-db
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
