apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gobland-legacy-backup-db
spec:
  storageClassName: csi-cinder-classic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
