FROM debian:stretch-slim

RUN apt-get update \
    && apt-get install -y wget \
    && wget https://downloads.mysql.com/archives/get/p/23/file/mysql-5.0.96-linux-x86_64-glibc23.tar.gz -O /tmp/mysql.tar.gz \
    && wget https://raw.githubusercontent.com/lordslair/foobar/master/k8s/gl-legacy/mysql/my.cnf -O /usr/local/mysql/my.cnf \
    && tar -xzf /tmp/mysql.tar.gz --no-same-owner -C /usr/local/mysql --strip-components=1 \
    && rm -rf /tmp/mysql.tar.gz \
    && mkdir /etc/mysql \
    && mv /usr/local/mysql/my.cnf /etc/mysql/my.cnf \
    && useradd --system mysql \
    && chown mysql:mysql /var/lib/mysql \
    && cd /usr/local/mysql \
    && ./scripts/mysql_install_db --datadir=/var/lib/mysql --user=mysql

EXPOSE 3306
CMD ["/usr/local/mysql/bin/mysqld_safe", "--defaults-file=/etc/mysql/my.cnf"]
