#!/usr/bin/perl
use strict;
use warnings;

use Term::ANSIColor;

my $log_dir = '/var/log';
my $backup_dir = '/backup';

my $log_list = `ls $log_dir/rsnapshot*.log`;
my @log_list = split('\n', $log_list);

printf("%-13s : %7s : %7s : %7s : %7s |\n", '============', '=======','=======','=======','=======');
printf("%-13s : %7s : %7s : %7s : %7s |\n", 'NAME', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY');
printf("%-13s : %7s : %7s : %7s : %7s |\n", '------------', '-------','-------','-------','-------');

foreach my $log (@log_list)
{
    if ( $log =~ /.*rsnapshot-([\w-]*).log$/)
    {
        my $name    = $1;
        my $end_h_r = my $end_d_r = my $end_w_r = my $end_m_r = colored('KO', 'bold red');
        my $size_h  = my $size_d = my $size_w = my $size_m = colored('N/A', 'bold red');
        my %Hash;
        my $color   = 'white';

        foreach my $interval ('hourly', 'daily', 'weekly', 'monthly')
        {
            $Hash{$interval}{'end'}  = colored('KO',  'bold red');
            $Hash{$interval}{'size'} = colored('N/A', 'bold red');
            if ( -d "$backup_dir/$name/$interval.0" )
            {
                $Hash{$interval}{'end'} = `grep '$interval:' $log | tail -1`;
                if ( $Hash{$interval}{'end'} =~ /successfully$/ ) { $color = 'bold green' } else { $color = 'bold red' }

                $Hash{$interval}{'size'} = `du -sh $backup_dir/$name/$interval.0  | awk {'print \$1'}`;
                chomp($Hash{$interval}{'size'});
                $Hash{$interval}{'size'} = colored($Hash{$interval}{'size'}, $color);
            }
            else
            {
                $Hash{$interval}{'size'} = colored('N/A', 'bold green');
            }
        }
        printf("%-25s : %18s : %18s : %18s : %18s |\n",colored($name, 'blue cyan'),
                                                       $Hash{'hourly'}{'size'},
                                                       $Hash{'daily'}{'size'},
                                                       $Hash{'weekly'}{'size'},
                                                       $Hash{'monthly'}{'size'});
    }
}

printf("%-13s : %7s : %7s : %7s : %7s |\n", '============', '=======','=======','=======','=======');
